#!/bin/bash

status=$(ip -br a | grep $1 | sed "s/  */ /g" |cut -d " " -f 2)

if [[ $status = "UP" ]]; then
    ip=$(ip -br a | grep $1 | sed "s/  */ /g" |cut -d " " -f 3)
    echo -e "%{F#0f0} 󰈀 %{F#fff} $ip %{F-}"
else
    echo -e "%{F#f00} 󰈀 %{F-}"
fi